[package]
name = "gui_druid"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = "0.13.4"
druid = { git = "https://github.com/linebender/druid", features=["im"] }
core = { path = "../core" }
audio = { path = "../audio" }
